export enum RoleUtilisateur {
  SINISTRE = 'SINISTRE',

  CITOYEN_AIDANT = 'CITOYEN_AIDANT',

  AUTORITE_LOCALE = 'AUTORITE_LOCALE',

  AGENT_AUTORITE = 'AGENT_AUTORITE',

  SECOURISTE = 'SECOURISTE',

  ADMINISTRATEUR = 'ADMINISTRATEUR',
}
