package fr.assistacrise.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModerationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModerationAllPropertiesEquals(Moderation expected, Moderation actual) {
        assertModerationAutoGeneratedPropertiesEquals(expected, actual);
        assertModerationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModerationAllUpdatablePropertiesEquals(Moderation expected, Moderation actual) {
        assertModerationUpdatableFieldsEquals(expected, actual);
        assertModerationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModerationAutoGeneratedPropertiesEquals(Moderation expected, Moderation actual) {
        assertThat(actual)
            .as("Verify Moderation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModerationUpdatableFieldsEquals(Moderation expected, Moderation actual) {
        assertThat(actual)
            .as("Verify Moderation relevant properties")
            .satisfies(a -> assertThat(a.getMotif()).as("check motif").isEqualTo(expected.getMotif()))
            .satisfies(a -> assertThat(a.getDateModeration()).as("check dateModeration").isEqualTo(expected.getDateModeration()))
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModerationUpdatableRelationshipsEquals(Moderation expected, Moderation actual) {
        assertThat(actual)
            .as("Verify Moderation relationships")
            .satisfies(a -> assertThat(a.getAdministrateur()).as("check administrateur").isEqualTo(expected.getAdministrateur()))
            .satisfies(a -> assertThat(a.getDemande()).as("check demande").isEqualTo(expected.getDemande()))
            .satisfies(a -> assertThat(a.getOffre()).as("check offre").isEqualTo(expected.getOffre()))
            .satisfies(a -> assertThat(a.getUtilisateurCible()).as("check utilisateurCible").isEqualTo(expected.getUtilisateurCible()));
    }
}
