package fr.assistacrise.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SalonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonAllPropertiesEquals(Salon expected, Salon actual) {
        assertSalonAutoGeneratedPropertiesEquals(expected, actual);
        assertSalonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonAllUpdatablePropertiesEquals(Salon expected, Salon actual) {
        assertSalonUpdatableFieldsEquals(expected, actual);
        assertSalonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonAutoGeneratedPropertiesEquals(Salon expected, Salon actual) {
        assertThat(actual)
            .as("Verify Salon auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonUpdatableFieldsEquals(Salon expected, Salon actual) {
        assertThat(actual)
            .as("Verify Salon relevant properties")
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonUpdatableRelationshipsEquals(Salon expected, Salon actual) {
        assertThat(actual)
            .as("Verify Salon relationships")
            .satisfies(a -> assertThat(a.getDemande()).as("check demande").isEqualTo(expected.getDemande()))
            .satisfies(a -> assertThat(a.getParticipants()).as("check participants").isEqualTo(expected.getParticipants()));
    }
}
